import type { IDisticts, IProvinces } from "~/types";

const provinceVTE: IProvinces = {
  id: 1,
  name_la: "ນະຄອນຫຼວງວຽງຈັນ",
  name_en: "Vientiane Capital",
  name_th: "นครหลวงเวียงจันทน์",
  code: "VTE",
};

const provincePHO: IProvinces = {
  id: 2,
  name_la: "ຜົ້ງສາລີ",
  name_en: "Phongsaly",
  name_th: "พงสาลี",
  code: "PHO",
};

const provinceLNT: IProvinces = {
  id: 3,
  name_la: "ຫຼວງນ້ຳທາ",
  name_en: "Luang Namtha",
  name_th: "หลวงน้ำทา",
  code: "LNT",
};

const provinceOUX: IProvinces = {
  id: 4,
  name_la: "ອຸດົມໄຊ",
  name_en: "Oudomxay",
  name_th: "อุดมไซ",
  code: "OUX",
};

const provinceBOK: IProvinces = {
  id: 5,
  name_la: "ບໍ່ແກ້ວ",
  name_en: "Bokeo",
  name_th: "บ่อแก้ว",
  code: "BOK",
};

const provinceLPB: IProvinces = {
  id: 6,
  name_la: "ຫຼວງພະບາງ",
  name_en: "Luang Prabang",
  name_th: "หลวงพระบาง",
  code: "LPB",
};

const provinceHUA: IProvinces = {
  id: 7,
  name_la: "ຫົວພັນ",
  name_en: "Houaphanh",
  name_th: "หัวพัน",
  code: "HUA",
};

const provinceXAY: IProvinces = {
  id: 8,
  name_la: "ໄຊຍະບູລີ",
  name_en: "Xayabury",
  name_th: "ไชยบุรี",
  code: "XAY",
};

const provinceXKH: IProvinces = {
  id: 9,
  name_la: "ຊຽງຂວາງ",
  name_en: "Xieng Khouang",
  name_th: "เชียงขวาง",
  code: "XKH",
};

const provinceVTP: IProvinces = {
  id: 10,
  name_la: "ວຽງຈັນ",
  name_en: "Vientiane Province",
  name_th: "แขวงเวียงจันทน์",
  code: "VTP",
};

const provinceBOL: IProvinces = {
  id: 11,
  name_la: "ບໍລິຄຳໄຊ",
  name_en: "Bolikhamxay",
  name_th: "บริคำไชย",
  code: "BOL",
};

const provinceKHM: IProvinces = {
  id: 12,
  name_la: "ຄຳມ່ວນ",
  name_en: "Khammouane",
  name_th: "คำม่วน",
  code: "KHM",
};

const provinceSVK: IProvinces = {
  id: 13,
  name_la: "ສະຫວັນນະເຂດ",
  name_en: "Savannakhet",
  name_th: "สะหวันนะเขต",
  code: "SVK",
};

const provinceSLV: IProvinces = {
  id: 14,
  name_la: "ສາລະວັນ",
  name_en: "Salavan",
  name_th: "สาละวัน",
  code: "SLV",
};

const provinceXEK: IProvinces = {
  id: 15,
  name_la: "ເຊກອງ",
  name_en: "Sekong",
  name_th: "เซกอง",
  code: "XEK",
};

const provinceCPS: IProvinces = {
  id: 16,
  name_la: "ຈຳປາສັກ",
  name_en: "Champasak",
  name_th: "จำปาศักดิ์",
  code: "CPS",
};

const provinceATP: IProvinces = {
  id: 17,
  name_la: "ອັດຕະປື",
  name_en: "Attapeu",
  name_th: "อัตตะปือ",
  code: "ATP",
};

const provinceXSB: IProvinces = {
  id: 18,
  name_la: "ໄຊສົມບູນ",
  name_en: "Xaysomboun",
  name_th: "ไซสมบูรณ์",
  code: "XSB",
};

const Districts: IDisticts[] = [
  // Vientiane Capital Districts
  {
    id: 1,
    name_la: "ເມືອງຈັນທະບູລີ",
    name_en: "Chanthabuly",
    name_th: "จันทบุรี",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01000",
    type: "Urban",
  },
  {
    id: 2,
    name_la: "ເມືອງສີໂຄດຕະບອງ",
    name_en: "Sikhottabong",
    name_th: "สีโคดตะบอง",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01001",
    type: "Urban",
  },
  {
    id: 3,
    name_la: "ເມືອງໄຊເສດຖາ",
    name_en: "Xaysetha",
    name_th: "ไชยเชษฐา",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01002",
    type: "Urban",
  },
  {
    id: 4,
    name_la: "ເມືອງສີສັດຕະນາກ",
    name_en: "Sisattanak",
    name_th: "สีสัตตนาค",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01003",
    type: "Urban",
  },
  {
    id: 5,
    name_la: "ເມືອງນາຊາຍທອງ",
    name_en: "Naxaithong",
    name_th: "นาซายทอง",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01004",
    type: "Rural",
  },
  {
    id: 6,
    name_la: "ເມືອງໄຊທານີ",
    name_en: "Xaythany",
    name_th: "ไซธานี",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01005",
    type: "Rural",
  },
  {
    id: 7,
    name_la: "ເມືອງຫາດຊາຍຟອງ",
    name_en: "Hadxayfong",
    name_th: "หาดทรายฟอง",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01006",
    type: "Urban",
  },
  {
    id: 8,
    name_la: "ເມືອງສັງທອງ",
    name_en: "Sangthong",
    name_th: "สังทอง",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01007",
    type: "Rural",
  },
  {
    id: 9,
    name_la: "ເມືອງປາກງື່ມ",
    name_en: "Parkngum",
    name_th: "ปากงึม",
    code: "VTE",
    provinceId: provinceVTE,
    postCode: "01008",
    type: "Rural",
  },

  // Phongsaly Province Districts
  {
    id: 201,
    name_la: "ເມືອງຜົ້ງສາລີ",
    name_en: "Phongsaly",
    name_th: "พงสาลี",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02000",
    type: "Urban",
  },
  {
    id: 202,
    name_la: "ເມືອງໃໝ່",
    name_en: "May",
    name_th: "ใหม่",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02010",
    type: "Rural",
  },
  {
    id: 203,
    name_la: "ເມືອງຂວາ",
    name_en: "Khoua",
    name_th: "ขวา",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02020",
    type: "Rural",
  },
  {
    id: 204,
    name_la: "ເມືອງສຳພັນ",
    name_en: "Samphan",
    name_th: "สัมพันธ์",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02030",
    type: "Rural",
  },
  {
    id: 205,
    name_la: "ເມືອງບຸນເໜືອ",
    name_en: "Boun Neua",
    name_th: "บุญเหนือ",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02040",
    type: "Rural",
  },
  {
    id: 206,
    name_la: "ເມືອງຍອດອູ",
    name_en: "Yot Ou",
    name_th: "ยอดอู",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02050",
    type: "Rural",
  },
  {
    id: 207,
    name_la: "ເມືອງບຸນໃຕ້",
    name_en: "Boun Tay",
    name_th: "บุญใต้",
    code: "PHO",
    provinceId: provincePHO,
    postCode: "02060",
    type: "Rural",
  },

  // Luang Namtha Province Districts
  {
    id: 301,
    name_la: "ເມືອງຫຼວງນ້ຳທາ",
    name_en: "Namtha",
    name_th: "หลวงน้ำทา",
    code: "LNT",
    provinceId: provinceLNT,
    postCode: "03000",
    type: "Urban",
  },
  {
    id: 302,
    name_la: "ເມືອງສິງ",
    name_en: "Sing",
    name_th: "สิง",
    code: "LNT",
    provinceId: provinceLNT,
    postCode: "03010",
    type: "Rural",
  },
  {
    id: 303,
    name_la: "ເມືອງລອງ",
    name_en: "Long",
    name_th: "ลอง",
    code: "LNT",
    provinceId: provinceLNT,
    postCode: "03020",
    type: "Rural",
  },
  {
    id: 304,
    name_la: "ເມືອງວຽງພູຄາ",
    name_en: "Viengphoukha",
    name_th: "เวียงภูคา",
    code: "LNT",
    provinceId: provinceLNT,
    postCode: "03030",
    type: "Rural",
  },
  {
    id: 305,
    name_la: "ເມືອງນາແລ",
    name_en: "Nalae",
    name_th: "นาแล",
    code: "LNT",
    provinceId: provinceLNT,
    postCode: "03040",
    type: "Rural",
  },

  // Oudomxay Province Districts
  {
    id: 401,
    name_la: "ເມືອງໄຊ",
    name_en: "Xay",
    name_th: "ไซ",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04000",
    type: "Urban",
  },
  {
    id: 402,
    name_la: "ເມືອງຫຼາ",
    name_en: "La",
    name_th: "หลา",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04010",
    type: "Rural",
  },
  {
    id: 403,
    name_la: "ເມືອງນາໝໍ້",
    name_en: "Namor",
    name_th: "นาหม้อ",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04020",
    type: "Rural",
  },
  {
    id: 404,
    name_la: "ເມືອງງາ",
    name_en: "Nga",
    name_th: "งา",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04030",
    type: "Rural",
  },
  {
    id: 405,
    name_la: "ເມືອງແບ່ງ",
    name_en: "Beng",
    name_th: "แบ่ง",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04040",
    type: "Rural",
  },
  {
    id: 406,
    name_la: "ເມືອງຮຸນ",
    name_en: "Houn",
    name_th: "ฮุน",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04050",
    type: "Rural",
  },
  {
    id: 407,
    name_la: "ເມືອງປາກແບ່ງ",
    name_en: "Pakbeng",
    name_th: "ปากแบ่ง",
    code: "OUX",
    provinceId: provinceOUX,
    postCode: "04060",
    type: "Rural",
  },
  {
    id: 501,
    name_la: "ເມືອງຫ້ວຍຊາຍ",
    name_en: "Houayxay",
    name_th: "ห้วยทราย",
    code: "BOK",
    provinceId: provinceBOK,
    postCode: "05000",
    type: "Urban",
  },
  {
    id: 502,
    name_la: "ເມືອງຕົ້ນເຜິ້ງ",
    name_en: "Tonpheung",
    name_th: "ต้นผึ้ง",
    code: "BOK",
    provinceId: provinceBOK,
    postCode: "05010",
    type: "Rural",
  },
  {
    id: 503,
    name_la: "ເມືອງເມິງ",
    name_en: "Meung",
    name_th: "เมิง",
    code: "BOK",
    provinceId: provinceBOK,
    postCode: "05020",
    type: "Rural",
  },
  {
    id: 504,
    name_la: "ເມືອງຜາອຸດົມ",
    name_en: "Pha Oudom",
    name_th: "ผาอุดม",
    code: "BOK",
    provinceId: provinceBOK,
    postCode: "05030",
    type: "Rural",
  },
  {
    id: 505,
    name_la: "ເມືອງປາກທາ",
    name_en: "Paktha",
    name_th: "ปากทา",
    code: "BOK",
    provinceId: provinceBOK,
    postCode: "05040",
    type: "Rural",
  },
  // Luang Prabang Province Districts
  {
    id: 601,
    name_la: "ເມືອງຫຼວງພະບາງ",
    name_en: "Luang Prabang",
    name_th: "หลวงพระบาง",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06000",
    type: "Urban",
  },
  {
    id: 602,
    name_la: "ເມືອງຊຽງເງິນ",
    name_en: "Xiengngeun",
    name_th: "เชียงเงิน",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06010",
    type: "Rural",
  },
  {
    id: 603,
    name_la: "ເມືອງນານ",
    name_en: "Nan",
    name_th: "นาน",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06020",
    type: "Rural",
  },
  {
    id: 604,
    name_la: "ເມືອງປາກອູ",
    name_en: "Pak Ou",
    name_th: "ปากอู",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06030",
    type: "Rural",
  },
  {
    id: 605,
    name_la: "ເມືອງນ້ຳບາກ",
    name_en: "Nambak",
    name_th: "น้ำบาก",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06040",
    type: "Rural",
  },
  {
    id: 606,
    name_la: "ເມືອງງອຍ",
    name_en: "Ngoy",
    name_th: "งอย",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06050",
    type: "Rural",
  },
  {
    id: 607,
    name_la: "ເມືອງປາກແຊງ",
    name_en: "Pakxeng",
    name_th: "ปากแซง",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06060",
    type: "Rural",
  },
  {
    id: 608,
    name_la: "ເມືອງໂພນໄຊ",
    name_en: "Phonxay",
    name_th: "โพนไชย",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06070",
    type: "Rural",
  },
  {
    id: 609,
    name_la: "ເມືອງຈອມເພັດ",
    name_en: "Chomphet",
    name_th: "จอมเพชร",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06080",
    type: "Rural",
  },
  {
    id: 610,
    name_la: "ເມືອງວຽງຄຳ",
    name_en: "Viengkham",
    name_th: "เวียงคำ",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06090",
    type: "Rural",
  },
  {
    id: 611,
    name_la: "ເມືອງພູຄູນ",
    name_en: "Phoukhoune",
    name_th: "ภูคูณ",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06100",
    type: "Rural",
  },
  {
    id: 612,
    name_la: "ເມືອງໂພນທອງ",
    name_en: "Phonthong",
    name_th: "โพนทอง",
    code: "LPB",
    provinceId: provinceLPB,
    postCode: "06110",
    type: "Rural",
  },

  // Houaphanh Province Districts
  {
    id: 701,
    name_la: "ເມືອງຊຳເໜືອ",
    name_en: "Xamneua",
    name_th: "ซำเหนือ",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07000",
    type: "Urban",
  },
  {
    id: 702,
    name_la: "ເມືອງຊຽງຄໍ້",
    name_en: "Xiengkhor",
    name_th: "เชียงค้อ",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07010",
    type: "Rural",
  },
  {
    id: 703,
    name_la: "ເມືອງວຽງໄຊ",
    name_en: "Viengxay",
    name_th: "เวียงไชย",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07020",
    type: "Rural",
  },
  {
    id: 704,
    name_la: "ເມືອງວຽງທອງ",
    name_en: "Viengthong",
    name_th: "เวียงทอง",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07030",
    type: "Rural",
  },
  {
    id: 705,
    name_la: "ເມືອງຊຳໃຕ້",
    name_en: "Xamtay",
    name_th: "ซำใต้",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07040",
    type: "Rural",
  },
  {
    id: 706,
    name_la: "ເມືອງສົບເບົາ",
    name_en: "Sop Bao",
    name_th: "สบเบา",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07050",
    type: "Rural",
  },
  {
    id: 707,
    name_la: "ເມືອງແອດ",
    name_en: "Et",
    name_th: "แอด",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07060",
    type: "Rural",
  },
  {
    id: 708,
    name_la: "ເມືອງກວັນ",
    name_en: "Kouan",
    name_th: "กวัน",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07070",
    type: "Rural",
  },
  {
    id: 709,
    name_la: "ເມືອງຊ່ອນ",
    name_en: "Xon",
    name_th: "ซ่อน",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07080",
    type: "Rural",
  },
  {
    id: 710,
    name_la: "ເມືອງຮ້ຽມ",
    name_en: "Hiam",
    name_th: "เหี้ยม",
    code: "HUA",
    provinceId: provinceHUA,
    postCode: "07090",
    type: "Rural",
  },
  // Xayabury Province Districts
  {
    id: 801,
    name_la: "ເມືອງໄຊຍະບູລີ",
    name_en: "Xayabury",
    name_th: "ไชยบุรี",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08000",
    type: "Urban",
  },
  {
    id: 802,
    name_la: "ເມືອງຄອບ",
    name_en: "Khop",
    name_th: "คอบ",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08010",
    type: "Rural",
  },
  {
    id: 803,
    name_la: "ເມືອງຊຽງຮ່ອນ",
    name_en: "Hongsa",
    name_th: "เชียงฮ่อน",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08020",
    type: "Rural",
  },
  {
    id: 804,
    name_la: "ເມືອງເງິນ",
    name_en: "Ngeun",
    name_th: "เงิน",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08030",
    type: "Rural",
  },
  {
    id: 805,
    name_la: "ເມືອງຊຽງຮ່ອນ",
    name_en: "Xieng_Hone",
    name_th: "เชียงฮ่อน",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08040",
    type: "Rural",
  },
  {
    id: 806,
    name_la: "ເມືອງປາກລາຍ",
    name_en: "Paklay",
    name_th: "ปากลาย",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08050",
    type: "Rural",
  },
  {
    id: 807,
    name_la: "ເມືອງແກ່ນທ້າວ",
    name_en: "Kenethao",
    name_th: "แก่นท้าว",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08060",
    type: "Rural",
  },
  {
    id: 808,
    name_la: "ເມືອງບໍ່ແຕນ",
    name_en: "Botene",
    name_th: "บ่อแตน",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08070",
    type: "Rural",
  },
  {
    id: 809,
    name_la: "ເມືອງທົ່ງມີໄຊ",
    name_en: "Thongmyxay",
    name_th: "ทุ่งมีไซ",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08080",
    type: "Rural",
  },
  {
    id: 810,
    name_la: "ເມືອງໄຊສະຖານ",
    name_en: "Xaisathan",
    name_th: "ไชยสถาน",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08090",
    type: "Rural",
  },
  {
    id: 811,
    name_la: "ເມືອງພຽງ",
    name_en: "Phiang",
    name_th: "เพียง",
    code: "XAY",
    provinceId: provinceXAY,
    postCode: "08100",
    type: "Rural",
  },

  // Xieng Khouang Province Districts
  {
    id: 901,
    name_la: "ເມືອງແປກ",
    name_en: "Paek",
    name_th: "แปก",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09000",
    type: "Urban",
  },
  {
    id: 902,
    name_la: "ເມືອງຄຳ",
    name_en: "Kham",
    name_th: "คำ",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09010",
    type: "Rural",
  },
  {
    id: 903,
    name_la: "ເມືອງໜອງແຮດ",
    name_en: "Nonghet",
    name_th: "หนองแฮด",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09020",
    type: "Rural",
  },
  {
    id: 904,
    name_la: "ເມືອງຄູນ",
    name_en: "Khoune",
    name_th: "คูน",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09030",
    type: "Rural",
  },
  {
    id: 905,
    name_la: "ເມືອງໝອກໄໝ່",
    name_en: "Morkmay",
    name_th: "หมอกใหม่",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09040",
    type: "Rural",
  },
  {
    id: 906,
    name_la: "ເມືອງພູກູດ",
    name_en: "Phookood",
    name_th: "ภูกูด",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09050",
    type: "Rural",
  },
  {
    id: 907,
    name_la: "ເມືອງຜາໄຊ",
    name_en: "Phaxay",
    name_th: "ผาไชย",
    code: "XKH",
    provinceId: provinceXKH,
    postCode: "09060",
    type: "Rural",
  },

  // Vientiane Province Districts
  {
    id: 1001,
    name_la: "ເມືອງໂພນໂຮງ",
    name_en: "Phonhong",
    name_th: "โพนโฮง",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10000",
    type: "Urban",
  },
  {
    id: 1002,
    name_la: "ເມືອງທຸລະຄົມ",
    name_en: "Thoulakhom",
    name_th: "ธุรคม",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10010",
    type: "Rural",
  },
  {
    id: 1003,
    name_la: "ເມືອງແກ້ວອຸດົມ",
    name_en: "Keo Oudom",
    name_th: "แก้วอุดม",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10020",
    type: "Rural",
  },
  {
    id: 1004,
    name_la: "ເມືອງກາສີ",
    name_en: "Kasy",
    name_th: "กาสี",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10030",
    type: "Rural",
  },
  {
    id: 1005,
    name_la: "ເມືອງວັງວຽງ",
    name_en: "Vangvieng",
    name_th: "วังเวียง",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10040",
    type: "Urban",
  },
  {
    id: 1006,
    name_la: "ເມືອງເຟືອງ",
    name_en: "Feuang",
    name_th: "เฟือง",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10050",
    type: "Rural",
  },
  {
    id: 1007,
    name_la: "ເມືອງຊະນະຄາມ",
    name_en: "Xanakham",
    name_th: "ชนะคาม",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10060",
    type: "Rural",
  },
  {
    id: 1008,
    name_la: "ເມືອງແມດ",
    name_en: "Mad",
    name_th: "แมด",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10070",
    type: "Rural",
  },
  {
    id: 1009,
    name_la: "ເມືອງວຽງຄຳ",
    name_en: "Viengkham",
    name_th: "เวียงคำ",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10080",
    type: "Rural",
  },
  {
    id: 1010,
    name_la: "ເມືອງຫີນເຫີບ",
    name_en: "Hinhurp",
    name_th: "หินเหิบ",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10090",
    type: "Rural",
  },
  {
    id: 1011,
    name_la: "ເມືອງໝື່ນ",
    name_en: "Muen",
    name_th: "หมื่น",
    code: "VTP",
    provinceId: provinceVTP,
    postCode: "10100",
    type: "Rural",
  },

  // Bolikhamxay Province Districts
  {
    id: 1101,
    name_la: "ເມືອງປາກຊັນ",
    name_en: "Paksane",
    name_th: "ปากซัน",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11000",
    type: "Urban",
  },
  {
    id: 1102,
    name_la: "ເມືອງທ່າພະບາດ",
    name_en: "Thaphabat",
    name_th: "ท่าพระบาท",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11010",
    type: "Rural",
  },
  {
    id: 1103,
    name_la: "ເມືອງປາກກະດິງ",
    name_en: "Pakkading",
    name_th: "ปากกะดิง",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11020",
    type: "Rural",
  },
  {
    id: 1104,
    name_la: "ເມືອງບໍລິຄັນ",
    name_en: "Borikhane",
    name_th: "บริคัน",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11030",
    type: "Rural",
  },
  {
    id: 1105,
    name_la: "ເມືອງຄຳເກີດ",
    name_en: "Khamkeut",
    name_th: "คำเกิด",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11040",
    type: "Rural",
  },
  {
    id: 1106,
    name_la: "ເມືອງວຽງທອງ",
    name_en: "Viengthong",
    name_th: "เวียงทอง",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11050",
    type: "Rural",
  },
  {
    id: 1107,
    name_la: "ເມືອງໄຊຈຳພອນ",
    name_en: "Xaychamphone",
    name_th: "ไซจำพร",
    code: "BOL",
    provinceId: provinceBOL,
    postCode: "11060",
    type: "Rural",
  },

  // Khammouane Province Districts
  {
    id: 1201,
    name_la: "ເມືອງທ່າແຂກ",
    name_en: "Thakhek",
    name_th: "ท่าแขก",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12000",
    type: "Urban",
  },
  {
    id: 1202,
    name_la: "ເມືອງມະຫາໄຊ",
    name_en: "Mahaxay",
    name_th: "มหาไชย",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12010",
    type: "Rural",
  },
  {
    id: 1203,
    name_la: "ເມືອງໜອງບົກ",
    name_en: "Nongbok",
    name_th: "หนองบก",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12020",
    type: "Rural",
  },
  {
    id: 1204,
    name_la: "ເມືອງຫີນບູນ",
    name_en: "Hineboune",
    name_th: "หินบูน",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12030",
    type: "Rural",
  },
  {
    id: 1205,
    name_la: "ເມືອງຍົມມະລາດ",
    name_en: "Yommalath",
    name_th: "ยมมะลาด",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12040",
    type: "Rural",
  },
  {
    id: 1206,
    name_la: "ເມືອງບົວລະພາ",
    name_en: "Boualapha",
    name_th: "บัวละพา",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12050",
    type: "Rural",
  },
  {
    id: 1207,
    name_la: "ເມືອງນາກາຍ",
    name_en: "Nakai",
    name_th: "นากาย",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12060",
    type: "Rural",
  },
  {
    id: 1208,
    name_la: "ເມືອງເຊບັ້ງໄຟ",
    name_en: "Sebangfay",
    name_th: "เซบั้งไฟ",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12070",
    type: "Rural",
  },
  {
    id: 1209,
    name_la: "ເມືອງໄຊບົວທອງ",
    name_en: "Xaibouthong",
    name_th: "ไชยบัวทอง",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12080",
    type: "Rural",
  },
  {
    id: 1210,
    name_la: "ເມືອງຄູນຄຳ",
    name_en: "Kounkham",
    name_th: "คูณคำ",
    code: "KHM",
    provinceId: provinceKHM,
    postCode: "12090",
    type: "Rural",
  },

  // Savannakhet Province Districts
  {
    id: 1301,
    name_la: "ເມືອງໄກສອນ ພົມວິຫານ",
    name_en: "Kaysone Phomvihane",
    name_th: "ไกสร พรมวิหาร",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13000",
    type: "Urban",
  },
  {
    id: 1302,
    name_la: "ເມືອງໄຊບູລີ",
    name_en: "Outhoumphone",
    name_th: "อุทุมพร",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13010",
    type: "Rural",
  },
  {
    id: 1303,
    name_la: "ເມືອງອຸທຸມພອນ",
    name_en: "Atsaphangthong",
    name_th: "อาจสะพังทอง",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13020",
    type: "Rural",
  },
  {
    id: 1304,
    name_la: "ເມືອງພີນ",
    name_en: "Phine",
    name_th: "พิน",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13030",
    type: "Rural",
  },
  {
    id: 1305,
    name_la: "ເມືອງເຊໂປນ",
    name_en: "Sepon",
    name_th: "เซโปน",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13040",
    type: "Rural",
  },
  {
    id: 1306,
    name_la: "ເມືອງນອງ",
    name_en: "Nong",
    name_th: "นอง",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13050",
    type: "Rural",
  },
  {
    id: 1307,
    name_la: "ເມືອງທ່າປາງທອງ",
    name_en: "Thapangthong",
    name_th: "ท่าปางทอง",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13060",
    type: "Rural",
  },
  {
    id: 1308,
    name_la: "ເມືອງສອງຄອນ",
    name_en: "Songkhone",
    name_th: "สองคอน",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13070",
    type: "Rural",
  },
  {
    id: 1309,
    name_la: "ເມືອງຈຳພອນ",
    name_en: "Champhone",
    name_th: "จำพร",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13080",
    type: "Rural",
  },
  {
    id: 1310,
    name_la: "ເມືອງຊົນນະບູລີ",
    name_en: "Xonnabuly",
    name_th: "ชนบุรี",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13090",
    type: "Rural",
  },
  {
    id: 1311,
    name_la: "ເມືອງໄຊບູລີ",
    name_en: "Xaybuly",
    name_th: "ไชยบุรี",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13100",
    type: "Rural",
  },
  {
    id: 1312,
    name_la: "ເມືອງວິລະບູລີ",
    name_en: "Vilabuly",
    name_th: "วิละบุรี",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13110",
    type: "Rural",
  },
  {
    id: 1313,
    name_la: "ເມືອງພະລານໄຊ",
    name_en: "Phalanxay",
    name_th: "พลาญไชย",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13120",
    type: "Rural",
  },
  {
    id: 1314,
    name_la: "ເມືອງໄຊພູທອງ",
    name_en: "Xayphouthong",
    name_th: "ไชยภูทอง",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13130",
    type: "Rural",
  },
  {
    id: 1315,
    name_la: "ເມືອງທ່າພະລານໄຊ",
    name_en: "Thaphalanxay",
    name_th: "ท่าพลาญไชย",
    code: "SVK",
    provinceId: provinceSVK,
    postCode: "13140",
    type: "Rural",
  },

  // Salavan Province Districts
  {
    id: 1401,
    name_la: "ເມືອງສາລະວັນ",
    name_en: "Salavan",
    name_th: "สาละวัน",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14000",
    type: "Urban",
  },
  {
    id: 1402,
    name_la: "ເມືອງຕະໂອ້ຍ",
    name_en: "Ta-Oy",
    name_th: "ตะโอ้ย",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14010",
    type: "Rural",
  },
  {
    id: 1403,
    name_la: "ເມືອງຕຸ້ມລານ",
    name_en: "Toumlane",
    name_th: "ตุ้มลาน",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14020",
    type: "Rural",
  },
  {
    id: 1404,
    name_la: "ເມືອງລະຄອນເພັງ",
    name_en: "Lakhonepheng",
    name_th: "ละครเพ็ง",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14030",
    type: "Rural",
  },
  {
    id: 1405,
    name_la: "ເມືອງວາປີ",
    name_en: "Vapy",
    name_th: "วาปี",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14040",
    type: "Rural",
  },
  {
    id: 1406,
    name_la: "ເມືອງຄົງເຊໂດນ",
    name_en: "Khongxedone",
    name_th: "คงเซโดน",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14050",
    type: "Rural",
  },
  {
    id: 1407,
    name_la: "ເມືອງເລົ່າງາມ",
    name_en: "Laongam",
    name_th: "เล่างาม",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14060",
    type: "Rural",
  },
  {
    id: 1408,
    name_la: "ເມືອງສະໝ້ວຍ",
    name_en: "Samuoi",
    name_th: "สมวย",
    code: "SLV",
    provinceId: provinceSLV,
    postCode: "14070",
    type: "Rural",
  },

  // Sekong Province Districts
  {
    id: 1501,
    name_la: "ເມືອງລະມາມ",
    name_en: "Lamarm",
    name_th: "ละมาม",
    code: "XEK",
    provinceId: provinceXEK,
    postCode: "15000",
    type: "Urban",
  },
  {
    id: 1502,
    name_la: "ເມືອງກະລຶມ",
    name_en: "Kaleum",
    name_th: "กะลึม",
    code: "XEK",
    provinceId: provinceXEK,
    postCode: "15010",
    type: "Rural",
  },
  {
    id: 1503,
    name_la: "ເມືອງດັກຈຶງ",
    name_en: "Dakcheung",
    name_th: "ดักจึง",
    code: "XEK",
    provinceId: provinceXEK,
    postCode: "15020",
    type: "Rural",
  },
  {
    id: 1504,
    name_la: "ເມືອງທ່າແຕງ",
    name_en: "Tha-Teng",
    name_th: "ท่าแตง",
    code: "XEK",
    provinceId: provinceXEK,
    postCode: "15030",
    type: "Rural",
  },

  // Champasak Province Districts
  {
    id: 1601,
    name_la: "ເມືອງປາກເຊ",
    name_en: "Pakxe",
    name_th: "ปากเซ",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16000",
    type: "Urban",
  },
  {
    id: 1602,
    name_la: "ເມືອງຊະນະສົມບູນ",
    name_en: "Sanasomboun",
    name_th: "ชนะสมบูรณ์",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16010",
    type: "Rural",
  },
  {
    id: 1603,
    name_la: "ເມືອງບາຈຽງຈະເລີນສຸກ",
    name_en: "Bachiangchaleunsook",
    name_th: "บาเจียงเจริญสุข",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16020",
    type: "Rural",
  },
  {
    id: 1604,
    name_la: "ເມືອງປາກຊ່ອງ",
    name_en: "Paksong",
    name_th: "ปากช่อง",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16030",
    type: "Urban",
  },
  {
    id: 1605,
    name_la: "ເມືອງປະທຸມພອນ",
    name_en: "Pathoumphone",
    name_th: "ปทุมพร",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16040",
    type: "Rural",
  },
  {
    id: 1606,
    name_la: "ເມືອງໂພນທອງ",
    name_en: "Phonthong",
    name_th: "โพนทอง",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16050",
    type: "Rural",
  },
  {
    id: 1607,
    name_la: "ເມືອງຈຳປາສັກ",
    name_en: "Champasak",
    name_th: "จำปาศักดิ์",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16060",
    type: "Rural",
  },
  {
    id: 1608,
    name_la: "ເມືອງສຸຂຸມາ",
    name_en: "Soukhouma",
    name_th: "สุขุมา",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16070",
    type: "Rural",
  },
  {
    id: 1609,
    name_la: "ເມືອງມູນລະປະໂມກ",
    name_en: "Mounlapamok",
    name_th: "มูลละปะโมก",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16080",
    type: "Rural",
  },
  {
    id: 1610,
    name_la: "ເມືອງໂຂງ",
    name_en: "Khong",
    name_th: "โขง",
    code: "CPS",
    provinceId: provinceCPS,
    postCode: "16090",
    type: "Rural",
  },

  // Attapeu Province Districts
  {
    id: 1701,
    name_la: "ເມືອງໄຊເສດຖາ",
    name_en: "Xaysetha",
    name_th: "ไชยเชษฐา",
    code: "ATP",
    provinceId: provinceATP,
    postCode: "17000",
    type: "Urban",
  },
  {
    id: 1702,
    name_la: "ເມືອງສາມັກຄີໄຊ",
    name_en: "Samakkixay",
    name_th: "สามัคคีไชย",
    code: "ATP",
    provinceId: provinceATP,
    postCode: "17010",
    type: "Urban",
  },
  {
    id: 1703,
    name_la: "ເມືອງສະໜາມໄຊ",
    name_en: "Sanamxay",
    name_th: "สนามไชย",
    code: "ATP",
    provinceId: provinceATP,
    postCode: "17020",
    type: "Rural",
  },
  {
    id: 1704,
    name_la: "ເມືອງສານໄຊ",
    name_en: "Sanxay",
    name_th: "สานไชย",
    code: "ATP",
    provinceId: provinceATP,
    postCode: "17030",
    type: "Rural",
  },
  {
    id: 1705,
    name_la: "ເມືອງພູວົງ",
    name_en: "Phouvong",
    name_th: "ภูวง",
    code: "ATP",
    provinceId: provinceATP,
    postCode: "17040",
    type: "Rural",
  },

  // Xaysomboun Province Districts
  {
    id: 1801,
    name_la: "ເມືອງອະນຸວົງ",
    name_en: "Anouvong",
    name_th: "อนุวง",
    code: "XSB",
    provinceId: provinceXSB,
    postCode: "18000",
    type: "Urban",
  },
  {
    id: 1802,
    name_la: "ເມືອງລ້ອງແຈ້ງ",
    name_en: "Longcheng",
    name_th: "ล่องแจ้ง",
    code: "XSB",
    provinceId: provinceXSB,
    postCode: "18010",
    type: "Rural",
  },
  {
    id: 1803,
    name_la: "ເມືອງທ່າໂທມ",
    name_en: "Thathom",
    name_th: "ท่าโทม",
    code: "XSB",
    provinceId: provinceXSB,
    postCode: "18020",
    type: "Rural",
  },
  {
    id: 1804,
    name_la: "ເມືອງລ້ອງຊານ",
    name_en: "Longsan",
    name_th: "ล่องซาน",
    code: "XSB",
    provinceId: provinceXSB,
    postCode: "18030",
    type: "Rural",
  },
  {
    id: 1805,
    name_la: "ເມືອງຮົ່ມ",
    name_en: "Hom",
    name_th: "ร่ม",
    code: "XSB",
    provinceId: provinceXSB,
    postCode: "18040",
    type: "Rural",
  },
];

export default Districts;
