import type { IProvinces } from "~/types";

const provinces: IProvinces[] = [
  {
    id: 1,
    name_la: "ນະຄອນຫຼວງວຽງຈັນ",
    name_en: "Vientiane Capital",
    name_th: "นครหลวงเวียงจันทน์",
    code: "VTE",
  },
  {
    id: 2,
    name_la: "ຜົ້ງສາລີ",
    name_en: "Phongsaly",
    name_th: "พงสาลี",
    code: "PHO",
  },
  {
    id: 3,
    name_la: "ຫຼວງນ້ຳທາ",
    name_en: "Luang Namtha",
    name_th: "หลวงน้ำทา",
    code: "LNT",
  },
  {
    id: 4,
    name_la: "ອຸດົມໄຊ",
    name_en: "Oudomxay",
    name_th: "อุดมไซ",
    code: "OUX",
  },
  {
    id: 5,
    name_la: "ບໍ່ແກ້ວ",
    name_en: "Bokeo",
    name_th: "บ่อแก้ว",
    code: "BOK",
  },
  {
    id: 6,
    name_la: "ຫຼວງພະບາງ",
    name_en: "Luang Prabang",
    name_th: "หลวงพระบาง",
    code: "LPB",
  },
  {
    id: 7,
    name_la: "ຫົວພັນ",
    name_en: "Houaphanh",
    name_th: "หัวพัน",
    code: "HUA",
  },
  {
    id: 8,
    name_la: "ໄຊຍະບູລີ",
    name_en: "Xayabury",
    name_th: "ไชยบุรี",
    code: "XAY",
  },
  {
    id: 9,
    name_la: "ຊຽງຂວາງ",
    name_en: "Xieng Khouang",
    name_th: "เชียงขวาง",
    code: "XKH",
  },
  {
    id: 10,
    name_la: "ວຽງຈັນ",
    name_en: "Vientiane Province",
    name_th: "แขวงเวียงจันทน์",
    code: "VTP",
  },
  {
    id: 11,
    name_la: "ບໍລິຄຳໄຊ",
    name_en: "Bolikhamxay",
    name_th: "บริคำไชย",
    code: "BOL",
  },
  {
    id: 12,
    name_la: "ຄຳມ່ວນ",
    name_en: "Khammouane",
    name_th: "คำม่วน",
    code: "KHM",
  },
  {
    id: 13,
    name_la: "ສະຫວັນນະເຂດ",
    name_en: "Savannakhet",
    name_th: "สะหวันนะเขต",
    code: "SVK",
  },
  {
    id: 14,
    name_la: "ສາລະວັນ",
    name_en: "Salavan",
    name_th: "สาละวัน",
    code: "SLV",
  },
  {
    id: 15,
    name_la: "ເຊກອງ",
    name_en: "Sekong",
    name_th: "เซกอง",
    code: "XEK",
  },
  {
    id: 16,
    name_la: "ຈຳປາສັກ",
    name_en: "Champasak",
    name_th: "จำปาศักดิ์",
    code: "CPS",
  },
  {
    id: 17,
    name_la: "ອັດຕະປື",
    name_en: "Attapeu",
    name_th: "อัตตะปือ",
    code: "ATP",
  },
  {
    id: 18,
    name_la: "ໄຊສົມບູນ",
    name_en: "Xaysomboun",
    name_th: "ไซสมบูรณ์",
    code: "XSB",
  },
];

export default provinces;
